name: Deploy API to AwardSpace (SFTP)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ftp-deploy:
    name: Upload via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy files via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /mediatekdocapi.atwebpages.com/